---
kind: Service
apiVersion: v1
metadata:
  name: turquoise-blue
  labels:
    app: turquoise
    version: blue
spec:
  selector:
    app: turquoise
    version: blue
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: turquoise-blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: turquoise
        version: blue
    spec:
      containers:
        - name: turquoise
          image: docker.io/joatmon08/turquoise:blue
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: TURQUOISE_APP_PORT
              value: "80"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: http_proxy
              value: $(NODE_NAME):4140