---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: dtabs.l5d.io
spec:
  scope: Namespaced
  group: l5d.io
  version: v1alpha1
  names:
    kind: DTab
    plural: dtabs
    singular: dtab
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: turquoise-namerd-config
data:
  config.yml: |-
    admin:
      ip: 0.0.0.0
      port: 9991

    namers:
    - kind: io.l5d.k8s
      experimental: true
      host: localhost
      port: 8001

    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: default

    interfaces:
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4100
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4101
      tls:
        certPath: /io.buoyant/namerd/certs/certificate.pem
        keyPath: /io.buoyant/namerd/certs/key.pk8
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4181
      tls:
        certPath: /io.buoyant/namerd/certs/certificate.pem
        keyPath: /io.buoyant/namerd/certs/key.pk8
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: 4321
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: 4322
      tls:
        certPath: /io.buoyant/namerd/certs/certificate.pem
        keyPath: /io.buoyant/namerd/certs/key.pk8

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: turquoise-namerd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: turquoise-namerd
    spec:
      volumes:
      - name: turquoise-namerd-config
        configMap:
          name: turquoise-namerd-config
      containers:
      - name: namerd
        image: buoyantio/namerd:1.3.2
        args:
        - /io.buoyant/namerd/config/config.yml
        ports:
        - name: thrift
          containerPort: 4100
        - name: thrift-tls
          containerPort: 4101
        - name: http
          containerPort: 4180
        - name: http-tls
          containerPort: 4181
        - name: mesh
          containerPort: 4321
        - name: mesh-tls
          containerPort: 4322
        - name: admin
          containerPort: 9991
        volumeMounts:
        - name: "turquoise-namerd-config"
          mountPath: "/io.buoyant/namerd/config"
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.8.5
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: turquoise-namerd
spec:
  selector:
    app: turquoise-namerd
  type: LoadBalancer
  ports:
  - name: thrift
    port: 4100
  - name: thrift-tls
    port: 4101
  - name: http
    port: 4180
  - name: http-tls
    port: 4181
  - name: mesh
    port: 4321
  - name: mesh-tls
    port: 4322
  - name: admin
    port: 9991
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: turquoise-namerctl-script
data:
  createNs.sh: |-
    #!/bin/sh

    set -e

    echo "
    /srv        => /#/io.l5d.k8s/default/http;
    /host       => /srv;
    /svc        => /host;
    " | namerctl dtab create internal -

    echo "
    /srv        => /#/io.l5d.k8s/default/http;
    /host       => /srv/turquoise-blue;
    /svc/*      => /host;
    " | namerctl dtab create external -
---
kind: Job
apiVersion: batch/v1
metadata:
  name: turquoise-namerctl
spec:
  template:
    metadata:
      name: turquoise-namerctl
    spec:
      volumes:
      - name: turquoise-namerctl-script
        configMap:
          name: turquoise-namerctl-script
          defaultMode: 0755
      containers:
      - name: namerctl
        image: linkerd/namerctl:0.8.6
        env:
        - name: NAMERCTL_BASE_URL
          value: http://turquoise-namerd.default.svc.cluster.local:4180
        command:
        - "/namerctl/createNs.sh"
        volumeMounts:
        - name: "turquoise-namerctl-script"
          mountPath: "/namerctl"
          readOnly: true
      restartPolicy: OnFailure