---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: turquoise-green
spec:
  destination:
    name: turquoise
  precedence: 2
  match:
    request:
      headers:
        user:
          regex: "joatmon08"
  route:
  - labels:
      version: green
