---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: turquoise-default
spec:
  destination:
    name: turquoise
  precedence: 1
  route:
  - labels:
      version: green
    weight: 100