kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: turquoise-green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: turquoise
        version: green
    spec:
      containers:
        - name: turquoise
          image: joatmon08/turquoise:green
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: TURQUOISE_APP_PORT
              value: "80"